# Generated by Django 4.0.5 on 2022-06-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_chart_stateabr_chart_title_stateentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stateentry',
            old_name='plot_id',
            new_name='plot',
        ),
    ]
