# Generated by Django 4.0.5 on 2022-06-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_stateentry_state_2_alter_stateentry_state_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateentry',
            name='state_2',
            field=models.CharField(blank=True, choices=[('ca', 'CA'), ('pa', 'PA'), ('ak', 'AK')], default='Empty', max_length=2),
        ),
        migrations.AlterField(
            model_name='stateentry',
            name='state_3',
            field=models.CharField(blank=True, choices=[('ca', 'CA'), ('pa', 'PA'), ('ak', 'AK')], default='Empty', max_length=2),
        ),
        migrations.AlterField(
            model_name='stateentry',
            name='state_4',
            field=models.CharField(blank=True, choices=[('ca', 'CA'), ('pa', 'PA'), ('ak', 'AK')], default='Empty', max_length=2),
        ),
        migrations.AlterField(
            model_name='stateentry',
            name='state_5',
            field=models.CharField(blank=True, choices=[('ca', 'CA'), ('pa', 'PA'), ('ak', 'AK')], default='Empty', max_length=2),
        ),
        migrations.AlterField(
            model_name='stateentry',
            name='state_6',
            field=models.CharField(blank=True, choices=[('ca', 'CA'), ('pa', 'PA'), ('ak', 'AK')], default='Empty', max_length=2),
        ),
    ]
